### ISSUE TITLE
image names in GUI get

### ISSUE THREAD

**Issue by philippb** [KeepSafe/ks-email-parser#18]
When in the GUI and loading an email, the GUI keeps the `[[name]]` around the image name. When saving the file, it adds new brackets, so that on the next load you have `[[[[name]]]]` and so on.

Strip the `[[]]` when loading from disk and add them back when saving.

**Comment by kcsaff** [comment]
Resolved in commit `0d9df412af8f9ef017a2289a7cfebba6cc95c13a`
