### ISSUE TITLE
GUI side by side layout

### ISSUE THREAD

**Issue by philippb** [KeepSafe/ks-email-parser#21]
`ks-email-parser gui` should make it easier to create emails in a visual way.

To improve this we want to be able to show final result of the email next to the edit mode.

![img_3407 1](https://cloud.githubusercontent.com/assets/374326/12566192/39a03bfa-c36d-11e5-81f2-8eb656190235.jpg)

On the left side the email will be displayed with all it's placeholders as text boxes that contain markdown. on the right side the email will be displayed in it's rendered from.

The rendered email will be updated when:
- courser unfocused a text field
- user presses `Preview`
- every 10 seconds if content has changed

**Comment by kcsaff** [comment]
I satisfied this requirement with PR #31 which has now been merged. In addition to the UI enhancement, we now generate most HTML using an actual templating system instead of the ad-hoc code that had been used.
