### ISSUE TITLE
GUI destroys formatting and removes placeholder

### ISSUE THREAD

**Issue by ZouhairB** [KeepSafe/ks-email-parser#39]
File: welcome_verify.xml

Original XML:
![image](https://cloud.githubusercontent.com/assets/1054088/14184042/0a7ba1fe-f728-11e5-8236-ca37fada1f65.png)

Original visual: 
![image](https://cloud.githubusercontent.com/assets/1054088/14184874/2b5ebfb0-f72c-11e5-9fa7-057135d1f458.png)

When I press "edit" in the GUI, it turns into this:
![image](https://cloud.githubusercontent.com/assets/1054088/14184888/3aabae1a-f72c-11e5-9523-5532848d2fc6.png)

notice that the {{url}} placeholder disappeared

**Comment by ca77y** [comment]
i can't reproduce it. works fine for me on chrome and safari. which browser are you using?

**Comment by ZouhairB** [comment]
chrome
