### ISSUE TITLE
Add {{local}} param to email parser

### ISSUE THREAD

**Issue by philippb** [KeepSafe/ks-email-parser#42]
In some emails we use locals in the email e.g.

```
###[{{code}}](https://accounts.getkeepsafe.com/redirect/acode/{{code}}/{{bundle}}?locale=en)
```

Translators tend to translate them but not reliable e.g.

```
###[{{code}}]( https://accounts.getkeepsafe.com/redirect/acode/{{code}}/{{bundle}}?locale=ar) 
```

I would like to introduce a `local` param that can be put in place instead of `en` in the original email and that gets replaced when rendering in all the local specific locals. 

The param might be to be named different then `{{local}}` to distinguished it from other client side params passed in.

## Task
Please come up with a solution and add documentation to how to use this.

**Comment by snejku** [comment]
@philippb 
> #### Link locale
> 
> `{link_locale}` is special placeholder, which is resolved by mapping located in `src/link_locale_mappings.json` during rendering.
> If email locale couldn't be mapped to link locale, it's `en` by default.
> 
> ```
> {
>   "email locale": "link locale",
>   "zh-TW-Hant": "zh"
> }
> ```
> If email locale will be `zh-TW-Hant`, then `[something](https://getkeepsafe.com/?locale={link_locale})` will be rendered as `[something](https://getkeepsafe.com/?locale=zh)`.
